spellchecker: aspell
matrix:
  - name: Check the english docs
    aspell:
      ignore-case: ""
      lang: en
    sources:
      - "docs/**/*.md"
      - "CONTRIBUTING.md"
      - "README.md"
    default_encoding: utf-8
    pipeline:
      - pyspelling.filters.context:
          context_visible_first: true
          escapes: \\[\\`~]
          delimiters:
            # Ignore multiline content between fences (fences can have 3 or more back ticks)
            # ```
            # content
            # ```
            - open: '^(?s)(?P<open>`{1,3})[^`]'
              close: '(?P=open)'
            # Ignore text between inline back ticks
            - open: '(?P<open>`)[^`]'
              close: '(?P=open)'
            # Ignore text in brackets [] and ()
            - open: '\['
              close: '\]'
            - open: '\('
              close: '\)'
            - open: '\{'
              close: '\}'
    dictionary:
      wordlists:
        - docs/spellcheck_exceptions.txt