name: Tests

on:
  push:
    branches: 
      - master
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Echo variables
      run: |
        echo ${{ github.push.repository.full_name }}
        echo ${{ github.repository }}
        echo ${{ github.event.pull_request.head.repo.full_name }}
        echo ${{ github.event.pull_request.head.ref }}
    
    - name: Report coverage
      if: (github.event.pull_request.head.repo.full_name || github.push.repository.full_name) == github.repository
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE }}
      with:
        coverageCommand: coverage xml
        debug: true
        coverageLocations: coverage.xml:coverage.py
